# Generated by Django 5.1.6 on 2025-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_rename_legend_photography_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
