# Generated by Django 5.1.6 on 2025-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('legend', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
