# Generated by Django 5.1.6 on 2025-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photography',
            old_name='legend',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
