# Generated by Django 5.1.6 on 2025-03-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_photography_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%m/%d/'),
        ),
    ]
