# Generated by Django 5.1.6 on 2025-03-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_photography_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
